# TOML Document for Terra-Validator Exporter(Pometheus & Grafana)

title = "TOML Document"

[Servers]
	[Servers.addr]
	rpc = "localhost:26657"
	rest = "localhost:1317"

[Validator]
operatorAddr = "cosmosvaloper14l0fp639yudfl46zauvv8rkzjgd4u0zk2aseys"

[Options]
listenPort = "26661"
