# TOML Document for Cosmos-Validator Exporter(Pometheus & Grafana)

title = "Cosmos-Validator Exporter TOML"
network = "cosmos"

# RPC-Server
[rpc]
address = "113.209.186.219:26657"

# Rest-server
[rest_server]
address = "113.209.186.219:1317"

[validator_info]
operatorAddress = "cosmosvaloper14l0fp639yudfl46zauvv8rkzjgd4u0zk2aseys"

[option]
exporterListenPort = "26661"
outputPrint = true
